# gRPC Server Configuration
grpc.server.port=${GRPC_SERVER_PORT:9090}
# SZTP Configuration
sztp.api.base.url=${SZTP_API_BASE_URL}
sztp.api.timeout.seconds=${SZTP_API_TIMEOUT_SECONDS:3000}
sztp.api.retry.attempts=${SZTP_API_RETRY_ATTEMPTS:3}
sztp.api.auth.certificate-path=${SZTP_API_AUTH_CERTIFICATE_PATH}
sztp.api.auth.certificate-password=${SZTP_API_AUTH_CERTIFICATE_PASSWORD}

# Logging
logging.level.com.nokia.grpc2sztp=${LOGGING_LEVEL_COM_NOKIA_GRPC2SZTP:DEBUG}
logging.level.okhttp3=${LOGGING_LEVEL_OKHTTP3:INFO}